### ISSUE TITLE
Is it possible to use Seurat SCTransform workflow in the FastIntegration?

### ISSUE THREAD

**Issue by nitinnarwade** [JinmiaoChenLab/FastIntegration#1]
Thank you for this wonderful package. It is really saving my neck.
However, is it possible to use Seurat's SCTransform workflow for the integration? 
Do you have any specific tutorials for it?

Thanks in advance :)
Nitin N.

**Comment by lmw123** [comment]
Hi. Nitin. Thanks for your interest. Unfortunately, currently, FastIntegration only supports data in log normalization.
