### ISSUE TITLE
scheduled cores did not deliver results

### ISSUE THREAD

**Issue by x1han** [JinmiaoChenLab/FastIntegration#3]
Hi, I'm finding a solution to integrate my dataset which has 1M cells these days, and **_FastIntegration_** is an extremely suitable tool for me. But I got some errors following, and I'm hoping there could be some advice for me.

There is the notebook I used:
https://1drv.ms/u/s!As1rAj5duIYvmE67BfF3RZkL3qRN?e=XrgZIX

And if you can not get the file through the link, contact me at hxsci@outlook.com

Hoping quick answer!
Thanks a lot!

**Comment by lmw123** [comment]
Hi Han,

Thanks for your interest in FastIntegration. 

From your codes, I feel hard to debug. One potential problem is that some of the sample contain too few cells. Could I know how many cells in each sample? Please feel free to contact me by li_mengwei@immunol.a-star.edu.sg. I am very glad to provide any helps.

Best,
Mengwei
