### ISSUE TITLE
How to manage metadata?

### ISSUE THREAD

**Issue by wajm** [JinmiaoChenLab/FastIntegration#4]
Hi,
Thank you for great tools.

after FastIntegration I reallized all original metadata of seurat objects are disappeard.
Is there any solution to manage metadata?

**Comment by lmw123** [comment]
Hi,

Thanks for your interests in FastIntegration. You can add metadata to the integrated seurat object by the following codes:

`

meta = lapply(rna.list, function(rna){return(rna@meta.data)}) #rna.list is the input object for FastIntegration
meta = do.call(rbind, meta)


rna.data = AddMetaData(rna.data, meta) # rna.data is the final Seurat object
`

Please let me know if you meet any problem. Thanks!

**Comment by wajm** [comment]
Hi, Thanks a lot.
