### ISSUE TITLE
Error:(converted from warning) No assay specified, setting assay as RNA by default.

### ISSUE THREAD

**Issue by Awakuhe** [JinmiaoChenLab/FastIntegration#5]
When I conducted this pipeline for integration, there is an error reporting: No assay specified, setting assay as RNA by default, during the FastFindAnchors function. 
Finding all pairwise anchors
  |==========================================================================================================| 100%, Elapsed 02:23
  |==========================================================================================================| 100%, Elapsed 01:08
  |=================================================                                                          |  46%, ETA 12:25:11Connected to your session in progress, last started 2023-Jan-06 10:58:24 UTC (3 minutes ago)
  |=================================================================================================| 100%, Elapsed 1 day 05:46:46
Merging data
  |===================================================================================================| 100%, Elapsed 01:52
Error: (converted from warning) No assay specified, setting assay as RNA by default.

How could I solve this problem

**Comment by lmw123** [comment]
Hi @Awakuhe,

Thanks for your interests in FastIntegration. May I know if there is file named "anchors.rds" in "FastIntegrationTmp/anchors/" folder. Thanks

Best,
Mengwei
