### ISSUE TITLE
DownloadDiscoData: Consistent missing samples in query, download aborted.

### ISSUE THREAD

**Issue by NathanSiemers** [JinmiaoChenLab/FastIntegration#6]
First, thank you for this tremendous resource.
I am finding samples that consistently cannot be retrieved from DownloadDiscoData.  The error handling of the function, with the tryCatch outside the for loop, means that the entire download is failing.

With the code below, sample 23 is failing consistently (sorry for poor fomatting, this is the first 5 columns of the row 23)

        sampleId projectId sampleType anatomicalSite                disease
 1595 GSM3753194 GSE130756     Cancer           <NA> acute myeloid leukemia

I wrote a modified function that ignored errors, and found that I could download 69 of the 188 samples, although some of the missing could have been excluded by later parts of the DownloadDiscoData function.

Code:

library(Seurat)
library(FastIntegration)
library(pbmcapply)
library(stringr) ## by the way this can be necessary and you need it in the vignette ;)
meta = FindSampleByMetadata()

## look for 'acute myeloid' in the disease column          
aml = meta[grep("acute myeloid", meta$disease), ]
dim(aml)

## that way we might get some paired normal samples etc.   
studylist = unique(aml$projectId)
## get all samples in study list                           
aml = meta[meta$projectId %in% studylist, ]

dim(aml)  ## 188 samples fit the criteria                  
## what platforms were used for these studies?             
table(aml$platform)

system('mkdir AMLData')

DownloadDiscoData(aml, dir = "./AMLData")

**Comment by lmw123** [comment]
Hi Nathan,

Thanks for your interests in DISCO. We have fixed this bug. Please try to download again. 

Best,
Mengwei

**Comment by lmw123** [comment]
By the way, we will release some new AML data today or tomorrow.

**Comment by NathanSiemers** [comment]
Wonderful to hear of new AML data coming!  I'm currently running the download described above and it has proceeded past that first problematic sample.  I'll let you know if I get any further errors.
It seems a shame that the DownloadDiscoData function doesn't check to see if a file already has been downloaded.  If md5 checksums are available in R perhaps I might create a download function that would be nicer to your servers :). 
Thank you!

**Comment by NathanSiemers** [comment]
ps: I do suggest adding 

library(stringr)

in the vignette, there's one part of FastIntegration that uses a function from it but does not load it.

**Comment by lmw123** [comment]
Hi Nathan,

Thank you so much for your great suggestions!!! I have added md5 information to the metadata table and rewrite the DownloadDiscoData function to allow resume download from previous download.

Please let me know if you meet any bugs or have any suggestion. Thanks

Best,
Mengwei

**Comment by NathanSiemers** [comment]
Yes, before I saw this message I noticed the changes in the meta file and code!  It's wonderful.

My only other problem is that downloads are failing after about 125 samples.  This seems to be right around the number of allowed R connections, so during download the connections are getting closed.

The connection options for url() are limited.  I tried writing a wrapper for url() that explicitly closed connections, but I realize I don't really understand connection objects in R, how they are passed and returned, so this attempt failed.

Any other ideas to work around the connection closing issue?  I'm on R 4.1.2

Thank you Mengwei!

**Comment by NathanSiemers** [comment]
the connections are *not* getting closed...

**Comment by NathanSiemers** [comment]
you may have done something about the connections also!  I'm currently well past the 125 sample/connection limit in my test download of the new code.  Also see a more verbose indication of download progress.  You are amazing Mengwei.
